/*!
 * updatemybrowser.org JavaScript Library v1
 * http://updatemybrowser.org/
 *
 * Copyright 2012, Joram van den Boezem
 * Licensed under the GPL Version 3 license.
 * http://www.gnu.org/licenses/gpl.html
 * 
 */
;if (typeof UMB === "undefined") {UMB = function() {}};

UMB.Browsers = {"chrome":{"id":"5","sort":"1","name":"Chrome","htmlname":"Chrome","shortname":"chrome","current":"19","minimum":"15","custom":null,"update_url":"http:\/\/www.google.com\/chrome","info_url":"http:\/\/www.google.com\/chrome\/intl\/en\/more\/index.html","iframe_allowed":null,"youtube_id":"nCgQDjiotG0","color":"00A651","description":"<p>\r\n\tChrome is designed to be fast in every possible way: It&#39;s quick to start up from your desktop, loads web pages in a snap, and runs complex web applications fast.<\/p>\r\n","published":"yes"},"firefox":{"id":"2","sort":"2","name":"Firefox","htmlname":"Firefox","shortname":"firefox","current":"13","minimum":"4","custom":null,"update_url":"http:\/\/www.getfirefox.com\/","info_url":"http:\/\/www.mozilla.org\/firefox\/central\/","iframe_allowed":null,"youtube_id":"N6H3t81LYRM","color":"F15A22","description":"<p>\r\n\tFirefox is built with you in mind, so it&#39;s easy and instinctive to use even the first time you try it. View Web pages way faster, using less of your computers memory.<\/p>\r\n","published":"yes"},"ie":{"id":"3","sort":"3","name":"Internet Explorer","htmlname":"<small>Internet Explorer<\/small>","shortname":"ie","current":"9","minimum":"8","custom":null,"update_url":"http:\/\/www.microsoft.com\/ie","info_url":"http:\/\/windows.microsoft.com\/en-GB\/internet-explorer\/products\/ie-9\/features","iframe_allowed":"1","youtube_id":"QC0Pk8Cxsu4","color":"64CCEC","description":"<p>\r\n\tThe new graphic capabilities and improved performance in Internet Explorer 9 set the stage for immersive and rich experiences. High-definition videos are smooth, graphics are clear and responsive, colors are true, and websites are interactive like never before.<\/p>\r\n","published":"yes"},"opera":{"id":"1","sort":"4","name":"Opera","htmlname":"Opera","shortname":"opera","current":"12","minimum":"10","custom":null,"update_url":"http:\/\/www.opera.com\/browser\/","info_url":"http:\/\/www.opera.com\/browser\/features\/","iframe_allowed":"1","youtube_id":"nGEbEUHXI_E","color":"ED1C24","description":"<p>\r\n\tMake your web browsing faster. Loading pages and running web applications is really snappy. You can even speed up browsing on slow connections, with Opera Turbo.<\/p>\r\n","published":"yes"},"safari":{"id":"4","sort":"5","name":"Safari","htmlname":"Safari","shortname":"safari","current":"5.1","minimum":"4","custom":null,"update_url":"http:\/\/www.apple.com\/safari\/","info_url":"http:\/\/www.apple.com\/safari\/whats-new.html","iframe_allowed":"1","youtube_id":"Uo6NvrFNqt4","color":"1C75BC","description":"<p>\r\n\tSafari isn&#39;t just the world&Atilde;&cent;&iuml;&iquest;&frac12;&iuml;&iquest;&frac12;s most innovative web browser. It changes the way you interact with the web. With great new features you&Atilde;&cent;&iuml;&iquest;&frac12;&iuml;&iquest;&frac12;ll become completely immersed in everything you see, touch, read, and watch. Oh, and browse.<\/p>\r\n","published":"yes"}};