<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */

// SyntaxHighlighter
$this->requireJsPublic('lib/SyntaxHighlighter/shCore.js');
$this->requireJsPublic('lib/SyntaxHighlighter/shBrushJScript.js');
$this->requireCssPublic('lib/SyntaxHighlighter/shCore.css');
$this->requireCssPublic('lib/SyntaxHighlighter/shThemeDefault.css');

?>

<div id="content">

	<h2>Widget documentation</h2>
	
	<h2>Basics</h2>
	<p>
		This is the most basic code to include the updatemybrowser.org <a href="widget">widget</a> on your page.
		Insert the code immediately before the closing &lt;/head&gt; tag in your page:
	</p>	
	
	<pre class="brush: js">
&lt;script type="text/javascript"&gt;
(function() {
	var s = document.createElement('script'); s.type = 'text/javascript'; s.async = true;
	s.src = ('https:'==document.location.protocol?'https://':'http://') + 'updatemybrowser.org/umb.js';
	var b = document.getElementsByTagName('script')[0]; b.parentNode.insertBefore(s, b);
})();
&lt;/script&gt;
	</pre>
	
	<p>
		This will automatically display the notification bar when updates for the browser are available.
	</p>
	
	<p>&nbsp;</p>
	
	<h2>Advanced</h2>
	
	<h3>Warning threshold</h3>
	
	<p>
		Two different notifications can be shown in the widget. If a user has a
		browser version lower than the minimum required version, they will see a
		more urgent upgrade message shown below:
	</p>
	
	<p>
		<img src="public/images/warning.png" width="759" height="224" alt="Warning" />
	</p>
	
	<p>
		Users for which an update is available, but having a browser version
		equal to or higher than the minimum required version, will see the
		following notification bar:
	</p>
		
	<p>
		<img src="public/images/update.png" width="759" height="224" alt="Update" />
	</p>
	
	<p>
		The widget is automatically updated with the recommended threshold for
		every browser, but you can override these settings by including the
		following configuration parameters somewhere in a &lt;script&gt; tag on your page:
	</p>
	
	<pre class="brush: js">
var _umb = {
	require: {
		chrome: 15,
		firefox: 4,
		ie: 8,
		opera: 10,
		safari: 4
	}
};
	</pre>
	
	<!--<h3>Display widget on page load</h3>
	
	<p>
		
	</p>
	
	<p>
		<img src="public/images/latest.png" width="759" height="224" alt="Latest" />
	</p>
	
	
	
	<pre class="brush: js">
var _umb = {
	require: {
		chrome: 15,
		firefox: 4,
		ie: 8,
		opera: 10,
		safari: 4
	}
};
	</pre>-->
	
	<p>
		More docs coming soon...
	</p>

</div>