<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */
?>

<div id="content">

	<h2>About</h2>
	
	<p>
		
	</p>
	
	<p>
		<a href="about/contact">Contact us</a><br/>
		<a href="about/docs">Widget documentation</a><br/>
		<a href="about/plugins">Plugins</a><br/>
		<a href="about/stats">Statistics</a><br/>
		
	</p>
	
	<p>&nbsp;</p>
	
	<h3>More resources:</h3>
	<p>
		<a href="http://www.github.com/hongaar/updatemybrowser">Source on Github</a>
	</p>	

</div>