<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */
?>

<div id="content">

	<h2>About</h2>
	<p>
		<a href="about/contact">Contact us</a><br/>
		<a href="about/docs">Widget documentation</a><br/>
		<a href="about/plugins">Plugins</a><br/>
	</p>
	
	<p>&nbsp;</p>
	
	<h3>Source code</h3>
	<p>
        Everything we do is open source. See what's under the hood on
        <a href="http://www.github.com/nabble/updatemybrowser">GitHub</a>
	</p>

    <h3>Who are you?</h3>
    <p>
        Update my Browser is a project by <a href="http://nabble.nl" target="_blank">Nabble</a>, a Dutch web design and development studio.
    </p>

</div>