<div id='content'>

	<h1><?php echo __("Administrators"); ?></h1>

		<?php
		$crud = $this->ACCrudList('browser',
			array(
				'fields' => array(
					'iframe_allowed' => array(
						'type' => 'boolean'
					),
					'sort' => array(
						'type' => 'sort'
					)
				),
				'list' => array(
					'show' => array('name', 'current', 'minimum', 'sort'),
					'main' => 'name'
				)
			)
		);
		echo $crud;
		?>
	
	<p>
		&nbsp;<br/>
		<a href="admin">Return</a>
	</p>
	
	<div class="clearfix"></div>

</div>
