<?php $this->requireJs('component/shortcut'); ?>

<?php echo $this->ajaxForm('_core/component:crudCommit', $this->id, 'ACCrudEdit'); ?>
	
	<dl class='crudEdit'>
		
		<?php foreach($this->labels as $fieldName => $fieldLabel) { ?>
			<dt title="<?php echo !empty($fieldLabel) ? $fieldLabel : $fieldName; ?>"><?php echo !empty($fieldLabel) ? $fieldLabel : $fieldName; ?></dt>
			<?php
			if ($this->item->has($fieldName)) {
				$value = $this->item->get($fieldName);
			} else {
				$value = "";
			}
			$prefix = '';
			$suffix = '';
			$class = '';
			$properties = '';
			$fieldType = $this->fields[$fieldName]['parsedType'];
						
			// Primary key
			if ($this->fields[$fieldName]['isPK'] === true) {
				$suffix .= " <img src='public/images/_core/crud/search_16.png' title='Primary key' />";
			}
			// Auto increment
			if ($this->fields[$fieldName]['isAutoIncrement'] === true) {
				$properties .= "readonly='readonly' ";
			}
			
			// Default value
			if (!empty($this->fields[$fieldName]['default']) && Ajde::app()->getRequest()->has('new')) {
				$value = $this->fields[$fieldName]['default'];
			}
			// Required
			if ($this->fields[$fieldName]['isRequired'] === true) {
				$properties .= "required='required' ";
				$suffix .= ' <span class="required">*</span>';
			}
			
			// Linked Model
			if ($value instanceof AjdeX_Model) {
				$value = $value->get($value->getDisplayField());
				$fieldType['type'] = AjdeX_Db::FIELD_TYPE_STRING;
				$properties .= "disabled='disabled' ";
			}

			switch ($fieldType['type']) {
				case AjdeX_Db::FIELD_TYPE_NUMERIC:
					?>
					<dd>
						<?php echo $prefix; ?>
						<input
							<?php echo $properties; ?>
							type="number"
							name="<?php echo $fieldName; ?>"
							value="<?php echo htmlentities($value); ?>"
						/>
						<?php echo $suffix; ?>
					</dd>
					<?php
					break;
				case AjdeX_Db::FIELD_TYPE_STRING:
				case AjdeX_Db::FIELD_TYPE_DATE:
					?>
					<dd>
						<?php echo $prefix; ?>
						<input
							<?php echo $properties; ?>
							type="text"
							maxlength="<?php echo $fieldType['length']; ?>"
							name="<?php echo $fieldName; ?>"
							value="<?php echo htmlentities($value); ?>"
						/>
						<?php echo $suffix; ?>
					</dd>
					<?php
					break;
				case AjdeX_Db::FIELD_TYPE_TEXT:
					?>
					<dd>
						<?php echo $prefix; ?>
						<textarea
							<?php echo $properties; ?>
							name="<?php echo $fieldName; ?>"
						><?php echo htmlentities($value); ?></textarea>
						<?php echo $suffix; ?>
					</dd>
					<?php
					break;
				case AjdeX_Db::FIELD_TYPE_ENUM:
					$options = explode(',', $fieldType['length']); ?>
					<dd>
						<?php echo $prefix; ?>
						<select
							<?php echo $properties; ?>
							name="<?php echo $fieldName; ?>">
							<?php foreach($options as $option) { 
								$option = trim($option, "'"); ?>
								<option value='<?php echo $option; ?>'
									<?php if ($option == $value) { echo "selected='selected'"; } ?>
									><?php echo $option; ?></option>
							<?php } ?>
						</select>
						<?php echo $suffix; ?>
					</dd>
					<?php
					break;
				default:
					?>
					<dd>
						DEBUG : no parser for fieldtype <?php echo $this->fields[$fieldName]['type']; ?>
					</dd>
					<?php
					break;
			}	
		}
		?>
		
		<dt>&nbsp;</dt>
		<dd>
			<button type="submit" class="save"><img src='public/images/_core/crud/accepted_16.png' /> Save</button>
			<a href="javascript:void(null);" class='cancel'><img src='public/images/_core/crud/cancel_16.png' /> Cancel</a>
		</dd>
	</dl>
		
</form>