<?php echo $this->ajaxForm('_core/component:crudCommit', $this->id, 'ACCrudList'); ?>

	<table class='crudList'>
	<thead>
		<tr>
			<th width="25"></th>
			<?php foreach($this->labels as $fieldName => $fieldLabel) {
				if (isset($this->options['show']) && (!in_array($fieldName, $this->options['show']))) { continue; } ?>
				<th><?php echo !empty($fieldLabel) ? $fieldLabel : $fieldName; ?></th>
			<?php } ?>
			<th width="120">
				<a href="javascript:void(null);" class='new'><img src='public/images/_core/crud/add_16.png' /> new</a>
			</th>
		</tr>
	</thead>
	<tbody>
	<?php foreach($this->items as $model) {?>
		<tr>
			<td><input type="checkbox" name="chk_<?php echo $model->getPK(); ?>" value="<?php echo $model->getPK(); ?>" /></td>
			<?php foreach($model->values() as $fieldName => $value) {
				if (isset($this->options['show']) && (!in_array($fieldName, $this->options['show']))) { continue; } ?>
				<?php
				// Linked Model
				if ($value instanceof AjdeX_Model) { ?>
					<td class="linkedModel" title="<?php echo $value->get($value->getDisplayField()); ?>"><?php echo $value->get($value->getDisplayField()); ?></td>
				<?php
				// Text value
				} else { ?>
					<td title="<?php echo $value; ?>"><?php echo htmlentities($value); ?></td>
				<?php } ?>			
			<?php } ?>
			<td>
				<a href="javascript:void(null);" class='edit'><img src='public/images/_core/crud/pencil_16.png' /> edit</a>
				<a href="javascript:void(null);" class='delete'><img src='public/images/_core/crud/cross_16.png' /> delete</a>
			</td>
		</tr>
	<?php } ?>
	</tbody>
	</table>

</form>