<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */
$this->requireCssTop('reset');

// jQuery 
$this->requireJsLibrary('jquery', '1');
//$this->requireJsPublic('lib/jquery-ui-1.8.16.custom.min.js');

// Fancybox
$this->requireJsPublic('lib/fancybox/jquery.fancybox-1.3.4.pack.js');
$this->requireCssPublic('lib/fancybox/jquery.fancybox-1.3.4.css');

// qTip
$this->requireJsPublic('lib/tip/jquery.tipsy.js');
$this->requireCssPublic('lib/tip/tipsy.css');

$module = Ajde::app()->getRoute()->getModule();
?>
<!-- Inspired by HTML5 Boilerplate -->
<!doctype html>
<html lang='<?php echo Ajde_Lang::getInstance()->getShortLang(); ?>' id='<?php echo Config::get('ident'); ?>'>
	<head>
		<meta charset='utf-8'>
		<!--[if IE]><![endif]-->
		<title><?php echo Ajde::app()->getDocument()->getTitle(); ?> - <?php echo Config::get('sitename'); ?></title>
		<meta name='description' content=''>
		<meta name='author' content=''>
		<base href='http://<?php echo Config::get('site_root'); ?>' />
		<link href='http://fonts.googleapis.com/css?family=Yellowtail|Cabin+Sketch:700|PT+Sans:400,700|PT+Sans+Narrow|Open+Sans:400,600,700' rel='stylesheet' type='text/css'>
		<?php echo Ajde::app()->getDocument()->getHead('css'); ?>
	</head>
	<!--[if lt IE 7 ]> <body class='ie6'> <![endif]-->
	<!--[if IE 7 ]>    <body class='ie7'> <![endif]-->
	<!--[if IE 8 ]>    <body class='ie8'> <![endif]-->
	<!--[if IE 9 ]>    <body class='ie9'> <![endif]-->
	<!--[if (gt IE 9)|!(IE)]><!--> <body> <!--<![endif]-->
		<div id='wrapper'>
			<div id='headerwrapper'>
				<div id='header'>
					<img src="public/images/logo.png" alt="Logo" />
					<h1>browser-update.org</h1>
					<h2><?php echo __('always the coolest browser'); ?></h2>
					<ul>
						<li><a class='<?php if ($module == 'browser') { echo 'active '; } ?>
							gray-shadow' href='browser'>
							<?php echo __('Browsercheck'); ?></a></li>
						<li><a class='<?php if ($module == 'widget') { echo 'active '; } ?>
							gray-shadow' href='widget'>
							<?php echo __('Widget'); ?></a></li>
						<li><a class='<?php if ($module == 'blog') { echo 'active '; } ?>
							gray-shadow' href='blog'>
							<?php echo __('Blog'); ?></a></li>
						<li><a class='<?php if ($module == 'about') { echo 'active '; } ?>
							gray-shadow' href='about'>
							<?php echo __('About'); ?></a></li>
					</ul>
				</div>
			</div>
			<?php echo Ajde::app()->getDocument()->getBody(); ?>				
			<div id='footerwrapper'>
				<div id='footer'>
					<p>
						<?php echo __('<strong>browser-update.org</strong> is an initiative to spread modern browsers <strong>like an epidemic</strong>. Websites these days have evolved to <strong>state of the art</strong> applications and todays browsers are built to serve them to you <strong>just right</strong>. Unfortunately, not everybody uses them, yet...'); ?>
					</p>
					<h2>http://<u>browser-update</u>.org</h2>
					<span>&copy; <?php echo date('Y'); ?> <?php echo __('All right reserved'); ?></span>
				</div>			
			</div>
		</div>
		<?php echo Ajde::app()->getDocument()->getScripts(); ?>
	</body>
</html>
